server:
  port: 8761

eureka:
  instance:
    hostname: https://eureka-server-cxgjf0gxbhbsfccz.canadacentral-01.azurewebsites.net
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false